[package]
name = "chacha8rand"
version = "0.1.0"
edition = "2024"
description = "ChaCha8Rand is a fast ChaCha8-based key-erasure CSPRNG"
repository = "https://github.com/nixberg/chacha8rand-rs"
license = "MIT"

[dependencies]
rand_core = "0.10"
